;;; Default tags (xhtml 1.0 strict)
(define-tag! a () #f)
(define-tag! abbr () #f)
(define-tag! acroynym () #f)
(define-tag! address () #f)
(define-tag! area ((alt "AREA")) #t)
(define-tag! base () #t)
(define-tag! bdo ((dir "ltr")) #f)
(define-tag! big () #f)
(define-tag! blockquote () #f)
(define-tag! body () #f)
(define-tag! br () #t)
(define-tag! button () #f)
(define-tag! caption () #f)
(define-tag! center () #f)
(define-tag! cite () #f)
(define-tag! code () #f)
(define-tag! col () #t)
(define-tag! colgroup () #f)
(define-tag! dd () #f)
(define-tag! del () #f)
(define-tag! dfn () #f)
(define-tag! div () #f)
(define-tag! dl () #f)
(define-tag! dt () #f)
(define-tag! em () #f)
(define-tag! fieldset () #f)
(define-tag! form ((action "!!unset!!")) #f)
(define-tag! frame () #t)
(define-tag! frameset () #f)
(define-tag! h1 () #f)
(define-tag! h2 () #f)
(define-tag! h3 () #f)
(define-tag! h4 () #f)
(define-tag! h5 () #f)
(define-tag! h6 () #f)
(define-tag! head () #f)
(define-tag! hr () #t)
(define-tag! html ((xml:lang "en") (lang "en")) #f)
(define-tag! i () #f)
(define-tag! iframe () #f)
(define-tag! img ((src "") (alt "[unset alt text]")) #t)
(define-tag! input () #t)
(define-tag! ins () #f)
(define-tag! kbd () #f)
(define-tag! label () #f)
(define-tag! legend () #f)
(define-tag! li () #f)
(define-tag! link () #t)
(define-tag! map ((name "name unset")) #f)
(define-tag! meta ((content "content unset")) #t)
(define-tag! noframes () #f)
(define-tag! noscript () #f)
(define-tag! object () #f)
(define-tag! ol () #f)
(define-tag! optgroup ((label "label unset")) #f)
(define-tag! option () #f)
(define-tag! p () #f)
(define-tag! param ((name "unset name")) #t)
(define-tag! pre () #f)
(define-tag! q () #f)
(define-tag! samp () #f)
(define-tag! script ((type "text/javascript")) #f)
(define-tag! select () #f)
(define-tag! small () #f)
(define-tag! span () #f)
(define-tag! strong () #f)
(define-tag! style ((type "text/css")) #f)
(define-tag! sub () #f)
(define-tag! sup () #f)
(define-tag! table () #f)
(define-tag! tbody () #f)
(define-tag! td () #f)
(define-tag! textarea ((rows "20") (cols "20")) #f)
(define-tag! tfoot () #f)
(define-tag! th () #f)
(define-tag! thead () #f)
(define-tag! title () #f)
(define-tag! tr () #f)
(define-tag! tt () #f)
(define-tag! ul () #f)
(define-tag! var () #f)
