py_linuxtuples.c File Reference
py_linuxtuples.c File Reference
Python API for tuple space clients.
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
#include "Python.h"
#include "tuple.h"
Data Structures
struct CtxObject
Python object, wrapper for a struct context.
Defines
#define SETENV_STRING
Functions
static PyObject * ctx_getattr (CtxObject *obj, char *name)
static PyObject * new_ctx (PyObject *self, PyObject *args)
static void ctx_dealloc (PyObject *self)
static struct tuple * PyTuple_to_LinuxTuple (PyObject *pytup, int puttable)
Pack a Python tuple into a Linuxtuples tuple.
static PyObject * LinuxTuple_to_PyTuple (struct tuple *t)
Unpack a Linuxtuples tuple and convert it to a Python tuple.
static PyObject * ctx_put_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_replace_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_get_read (CtxObject *pyctx, PyObject *args, struct tuple *(*func)(struct tuple *,struct context *), int blocking)
static PyObject * ctx_get_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_read_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_get_nb_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_read_nb_tuple (PyObject *self, PyObject *args)
static PyObject * ctx_dump_tuple_space (PyObject *self, PyObject *args)
static PyObject * ctx_count_tuple_space (PyObject *self, PyObject *args)
static PyObject * ctx_tuple_server_log (PyObject *self, PyObject *args)
static PyObject * py_random_int (PyObject *self, PyObject *args)
void initlinuxtuples ()
Initialization function for the module _must_ be called initlinuxtuples.
Variables
staticforward PyTypeObject CtxType
static char ctx_put_doc_string []
static char ctx_replace_doc_string []
static char ctx_get_doc_string []
static char ctx_read_doc_string []
static char ctx_get_nb_doc_string []
static char ctx_read_nb_doc_string []
static char ctx_dump_doc_string []
static char ctx_count_doc_string []
static char ctx_log_doc_string []
static PyMethodDef linuxtuples_methods []
List of functions defined in the linuxtuples module.
static PyMethodDef ctx_methods []
static char py_random_int_doc_string []
static char linuxtuples_doc_string []
static char ctx_doc_string []
static char new_ctx_doc_string []
Detailed Description
Python API for tuple space clients.
The best documentation for this is to look at the examples provided in the Python source code for how to extend the language with modules and objects. The 1.5.2 codebase is easy to read; look for xxobject.c and xxmodule.c.
Definition in file py_linuxtuples.c.
Define Documentation
#define SETENV_STRING
Value:
"\nUnable to find the environment variables (LINUXTUPLES_HOST,\n" \
"LINUXTUPLES_PORT). Please set them."
Definition at line 173 of file py_linuxtuples.c.
Referenced by new_ctx().
Function Documentation
static PyObject * ctx_count_tuple_space (PyObject * self, PyObject * args) [static]
See also:
ctx_dump_doc_string
Definition at line 687 of file py_linuxtuples.c.
References count_tuple_space(), CtxObject::ctx, tuple_list::next, PyTuple_to_LinuxTuple(), and tuple_list::tup.
static void ctx_dealloc (PyObject * self) [static]
Definition at line 219 of file py_linuxtuples.c.
References CtxObject::ctx, and context::sock.
static PyObject * ctx_dump_tuple_space (PyObject * self, PyObject * args) [static]
See also:
ctx_dump_doc_string
Definition at line 598 of file py_linuxtuples.c.
References CtxObject::ctx, dump_tuple_space(), LinuxTuple_to_PyTuple(), tuple_list::next, PyTuple_to_LinuxTuple(), and tuple_list::tup.
static PyObject * ctx_get_nb_tuple (PyObject * self, PyObject * args) [static]
See also:
ctx_get_nb_doc_string
Definition at line 563 of file py_linuxtuples.c.
References ctx_get_read(), and get_nb_tuple().
static PyObject * ctx_get_read (CtxObject * pyctx, PyObject * args, struct tuple *(*)(struct tuple *, struct context *) func, int blocking) [static]
Definition at line 464 of file py_linuxtuples.c.
References CtxObject::ctx, destroy_tuple(), LinuxTuple_to_PyTuple(), and PyTuple_to_LinuxTuple().
Referenced by ctx_get_nb_tuple(), ctx_get_tuple(), ctx_read_nb_tuple(), and ctx_read_tuple().
static PyObject * ctx_get_tuple (PyObject * self, PyObject * args) [static]
See also:
ctx_get_doc_string
Definition at line 528 of file py_linuxtuples.c.
References ctx_get_read(), and get_tuple().
static PyObject * ctx_getattr (CtxObject * obj, char * name) [static]
Definition at line 164 of file py_linuxtuples.c.
References ctx_doc_string.
static PyObject * ctx_put_tuple (PyObject * self, PyObject * args) [static]
Definition at line 372 of file py_linuxtuples.c.
References CtxObject::ctx, destroy_tuple(), put_tuple(), and PyTuple_to_LinuxTuple().
static PyObject * ctx_read_nb_tuple (PyObject * self, PyObject * args) [static]
See also:
ctx_read_nb_doc_string
Definition at line 581 of file py_linuxtuples.c.
References ctx_get_read(), and read_nb_tuple().
static PyObject * ctx_read_tuple (PyObject * self, PyObject * args) [static]
See also:
ctx_read_doc_string
Definition at line 546 of file py_linuxtuples.c.
References ctx_get_read(), and read_tuple().
static PyObject * ctx_replace_tuple (PyObject * self, PyObject * args) [static]
Definition at line 416 of file py_linuxtuples.c.
References CtxObject::ctx, destroy_tuple(), PyTuple_to_LinuxTuple(), and replace_tuple().
static PyObject * ctx_tuple_server_log (PyObject * self, PyObject * args) [static]
See also:
ctx_log_doc_string
Definition at line 761 of file py_linuxtuples.c.
References CtxObject::ctx, and tuple_server_log().
initlinuxtuples (void)
Initialization function for the module _must_ be called initlinuxtuples.
Definition at line 804 of file py_linuxtuples.c.
References linuxtuples_doc_string.
static PyObject * LinuxTuple_to_PyTuple (struct tuple * t) [static]
Unpack a Linuxtuples tuple and convert it to a Python tuple.
Definition at line 315 of file py_linuxtuples.c.
References element::d, element::data, tuple::elements, element::i, element::len, tuple::num_elts, element::ptr, element::t, and element::tag.
Referenced by ctx_dump_tuple_space(), and ctx_get_read().
static PyObject * new_ctx (PyObject * self, PyObject * args) [static]
Definition at line 188 of file py_linuxtuples.c.
References CtxObject::ctx, CtxType, get_server_portnumber(), context::id, context::peername, context::portnumber, and SETENV_STRING.
static PyObject * py_random_int (PyObject * self, PyObject * args) [static]
See also:
py_random_int_doc_string
Definition at line 780 of file py_linuxtuples.c.
References random_int().
static struct tuple * PyTuple_to_LinuxTuple (PyObject * pytup, int puttable) [static, read]
Pack a Python tuple into a Linuxtuples tuple.
If it's for a PUT, do not permit '?' wildcards. But they're OK for GET and READ templates.
Definition at line 256 of file py_linuxtuples.c.
References element::d, element::data, tuple::elements, element::i, tuple::num_elts, element::s, tuple::string_length, tuple::string_space, element::t, and element::tag.
Referenced by ctx_count_tuple_space(), ctx_dump_tuple_space(), ctx_get_read(), ctx_put_tuple(), and ctx_replace_tuple().
Variable Documentation
static char ctx_count_doc_string [static]
Initial value:
        "n = conn.count( [template_list] )\n"
        "Return a count of the tuples in the tuple space. If no template\n"
        "list is given, count all the tuples. If there is a template\n"
        "list, return only the number of tuples that match at least one\n"
        "template."
Definition at line 74 of file py_linuxtuples.c.
char ctx_doc_string[] [static]
Initial value:
        "This is a connection to a tuple server. Its methods give access to\n"
        "tuple space.\n"
        "\n"
        "The put(tuple) method lets you put a tuple into the tuple space.\n"
        "get(template) removes a tuple that matches the template (where None is\n"
        "used as a wildcard), blocking until a matching tuple becomes\n"
        "available. read(template) is like get(), but it returns a copy of the\n"
        "tuple, leaving the original in tuple space.\n"
        "\n"
        "get_nonblocking() and read_nonblocking() are non-blocking versions of\n"
        "get() and read(), which return None if a matching tuple is not\n"
        "available.\n"
        "\n"
        "The dump() method returns a list of the tuples in tuple space. If\n"
        "supplied with a list of templates as an argument, it will return a\n"
        "list of only those tuples that match at least one template.\n"
        "\n"
        "The log() method prints a running log of tuple server activity to\n"
        "stdout. It should be called in a \"while 1:\" loop."
Definition at line 113 of file py_linuxtuples.c.
Referenced by ctx_getattr().
static char ctx_dump_doc_string [static]
Initial value:
        "tuple_list = conn.dump( [template_list] )\n"
        "Return a list of the tuples in the tuple space. If no template\n"
        "list is given, return all the tuples. If there is a template\n"
        "list, return only the tuples that match at least one template."
Definition at line 73 of file py_linuxtuples.c.
static char ctx_get_doc_string [static]
Initial value:
        "tuple = conn.get(template)\n"
        "Get a tuple from tuple space. Items in the returned tuple\n"
        "must match any non-None items in the template. Nones are\n"
        "wildcards. This call blocks until a matching tuple is found."
Definition at line 69 of file py_linuxtuples.c.
static char ctx_get_nb_doc_string [static]
Initial value:
        "tuple = conn.get_nonblocking(template)\n"
        "Get a tuple from tuple space. Items in the returned tuple\n"
        "must match any non-None items in the template. Nones are\n"
        "wildcards. If no matching tuple is found, returns None."
Definition at line 71 of file py_linuxtuples.c.
static char ctx_log_doc_string [static]
Initial value:
        "Dump a continuous log of tuple space activity to stdout. Call this\n"
        "method in a \"while 1:\" loop. Looping in Python rather than C\n"
        "means that you can break out of the loop easily with control-C,\n"
        "and you can put other code in the loop."
Definition at line 75 of file py_linuxtuples.c.
static PyMethodDef ctx_methods [static]
Initial value:
 {
        {"put", ctx_put_tuple, METH_VARARGS,
         ctx_put_doc_string},
        {"get", ctx_get_tuple, METH_VARARGS,
         ctx_get_doc_string},
        {"read", ctx_read_tuple, METH_VARARGS,
         ctx_read_doc_string},
        {"get_nonblocking", ctx_get_nb_tuple, METH_VARARGS,
         ctx_get_nb_doc_string},
        {"read_nonblocking", ctx_read_nb_tuple, METH_VARARGS,
         ctx_read_nb_doc_string},
        {"replace", ctx_replace_tuple, METH_VARARGS,
         ctx_replace_doc_string},
        {"dump", ctx_dump_tuple_space, METH_VARARGS,
         ctx_dump_doc_string},
        {"count", ctx_count_tuple_space, METH_VARARGS,
         ctx_count_doc_string},
        {"log", ctx_tuple_server_log, METH_VARARGS,
         ctx_log_doc_string},
        {NULL, NULL, 0, NULL}
}
Definition at line 77 of file py_linuxtuples.c.
static char ctx_put_doc_string [static]
Initial value:
        "conn.put(tuple)\n" "Put a tuple into tuple space."
Definition at line 67 of file py_linuxtuples.c.
static char ctx_read_doc_string [static]
Initial value:
        "tuple = conn.read(template)\n"
        "Read a copy of a tuple from tuple space. Items in the\n"
        "returned tuple must match any non-None items in the template.\n"
        "Nones are wildcards. This call blocks until a matching\n"
        "tuple is found."
Definition at line 70 of file py_linuxtuples.c.
static char ctx_read_nb_doc_string [static]
Initial value:
        "tuple = conn.read_nonblocking(template)\n"
        "Read a copy of a tuple from tuple space. Items in the\n"
        "returned tuple must match any non-None items in the template.\n"
        "Nones are wildcards. If no matching tuple is found, returns\n"
        "None."
Definition at line 72 of file py_linuxtuples.c.
static char ctx_replace_doc_string [static]
Initial value:
        "conn.replace(templ, replacement)\n" "Remove all tuples matching the template, and put a single replacement into the space."
Definition at line 68 of file py_linuxtuples.c.
static PyTypeObject CtxType
Initial value:
 {
        PyObject_HEAD_INIT(NULL)
                0,
        "Ctx",
        sizeof(CtxObject),
        0,
        ctx_dealloc,
        0,
        (getattrfunc) ctx_getattr,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
}
Definition at line 54 of file py_linuxtuples.c.
Referenced by new_ctx().
char linuxtuples_doc_string[] [static]
Initial value:
        "This is the Python client API for the linuxtuples tuple server. The\n"
        "connect() method returns a connection to the tuple server. The\n"
        "random() method returns a 32-bit integer taken from /dev/urandom."
Definition at line 106 of file py_linuxtuples.c.
Referenced by initlinuxtuples().
static PyMethodDef linuxtuples_methods [static]
Initial value:
 {
        {"connect", new_ctx, METH_VARARGS, new_ctx_doc_string},
        {"random", py_random_int, METH_VARARGS, py_random_int_doc_string},
        {NULL, NULL}
}
List of functions defined in the linuxtuples module.
Definition at line 76 of file py_linuxtuples.c.
char new_ctx_doc_string[] [static]
Initial value:
        "conn = connect()          [ get host and port# from env. vars]\n"
        "conn = connect(string,int)   [ set host and port# explicitly ]\n"
        "Return a connection to the tuple server."
Definition at line 179 of file py_linuxtuples.c.
static char py_random_int_doc_string [static]
Initial value:
        "Return a 32-bit random integer, taken from /dev/urandom."
Definition at line 99 of file py_linuxtuples.c.