tuple.c File Reference
tuple.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <sched.h>
#include <malloc.h>
#include "tuple.h"
Defines
#define PERROR(x) fprintf(stderr, __FILE__":%d ", __LINE__); perror(x)
Functions
void print_tuple_stderr (struct tuple *s)
void print_tuple (struct tuple *s)
void print_element_stderr (struct element *e)
struct tuple * tuple_tuple_field (struct tuple *s, int n)
int get_server_portnumber (struct context *ctx)
void print_element (struct element *e)
static struct tuple * make_tuple_internal (char *fmt, va_list ap)
struct tuple * make_tuple (char *fmt,...)
void destroy_tuple (struct tuple *t)
int tuples_match (struct tuple *s, struct tuple *t)
unsigned int random_int (void)
int send_chunk (struct context *ctx, char *buf, int bytes_to_send)
int send_tuple (struct context *ctx, struct tuple *t)
int recv_chunk (struct context *ctx, char *buf, int size)
struct tuple * recv_tuple (struct context *ctx)
static int open_client_socket (struct context *ctx)
int put_tuple (struct tuple *s, struct context *ctx)
int replace_tuple (struct tuple *template, struct tuple *replacement, struct context *ctx)
struct tuple * get_tuple (struct tuple *s, struct context *ctx)
struct tuple * read_tuple (struct tuple *template_tuple, struct context *ctx)
struct tuple * get_nb_tuple (struct tuple *template_tuple, struct context *ctx)
struct tuple * read_nb_tuple (struct tuple *template_tuple, struct context *ctx)
struct tuple_list * dump_tuple_space (struct tuple_list *templates, struct context *ctx)
int count_tuple_space (struct tuple_list *templates, struct context *ctx, int *result)
int tuple_server_log (FILE *stream, struct context *ctx)
static struct element * tuple_field (struct tuple *s, int n)
int tuple_int_field (struct tuple *s, int n)
double tuple_double_field (struct tuple *s, int n)
char * tuple_string_field (struct tuple *s, int *len, int n)
Variables
int i_am_server = 0
char logbuf [LOGBUFSIZE]
int logptr = 0
Define Documentation
#define PERROR (x) fprintf(stderr, __FILE__":%d ", __LINE__); perror(x)
Definition at line 96 of file tuple.c.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), make_tuple_internal(), open_client_socket(), put_tuple(), read_nb_tuple(), read_tuple(), recv_chunk(), recv_tuple(), replace_tuple(), send_chunk(), send_tuple(), and tuple_server_log().
Function Documentation
int count_tuple_space (struct tuple_list * templates, struct context * ctx, int * result)
This works just like dump_tuple_space, but instead of sending back a list of all the matching tuples, we just send back a count of how many tuples match.
Definition at line 1134 of file tuple.c.
References COUNT, tuple_list::next, open_client_socket(), PERROR, recv_chunk(), send_chunk(), and send_tuple().
Referenced by ctx_count_tuple_space().
void destroy_tuple (struct tuple * t)
Deallocate all the storage for a tuple.
Definition at line 381 of file tuple.c.
References tuple::elements, and tuple::string_space.
Referenced by ctx_get_read(), ctx_put_tuple(), ctx_replace_tuple(), handle_get_read(), handle_replace(), and main().
struct tuple_list* dump_tuple_space (struct tuple_list * templates, struct context * ctx) [read]
Transmit a list of templates to the server, with an op code of DUMP. The server will respond by sending back a list of the matching tuples.
Definition at line 1057 of file tuple.c.
References DBGPRINTF, DUMP, tuple_list::next, open_client_socket(), PERROR, recv_chunk(), recv_tuple(), send_chunk(), send_tuple(), and tuple_list::tup.
Referenced by ctx_dump_tuple_space().
struct tuple* get_nb_tuple (struct tuple * template_tuple, struct context * ctx) [read]
Definition at line 953 of file tuple.c.
References GET_NB, context::id, open_client_socket(), PERROR, print_tuple_stderr(), recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_get_nb_tuple().
int get_server_portnumber (struct context * ctx)
Attempt to get the server name and port number from environment variables.
Returns:
0 if successful, 1 otherwise.
Definition at line 110 of file tuple.c.
References context::peername, context::portnumber, PORTNUMBER_ENVVAR, and SERVERNAME_ENVVAR.
Referenced by main(), and new_ctx().
struct tuple* get_tuple (struct tuple * s, struct context * ctx) [read]
Definition at line 864 of file tuple.c.
References DBGPRINTF, GET, context::id, open_client_socket(), PERROR, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_get_tuple(), and main().
struct tuple* make_tuple (char * fmt, ...) [read]
Create a tuple or template, starting from a printf-style variable argument list.
Definition at line 366 of file tuple.c.
References make_tuple_internal(), and va_list.
Referenced by main().
static struct tuple* make_tuple_internal (char * fmt, va_list ap) [static, read]
Definition at line 292 of file tuple.c.
References element::d, element::data, tuple::elements, EXIT, element::i, tuple::num_elts, PERROR, element::s, tuple::string_space, element::t, and element::tag.
Referenced by make_tuple().
static int open_client_socket (struct context * ctx) [static]
Definition at line 720 of file tuple.c.
References context::id, context::peername, PERROR, context::portnumber, and context::sock.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), put_tuple(), read_nb_tuple(), read_tuple(), replace_tuple(), and tuple_server_log().
void print_element (struct element * e)
Definition at line 134 of file tuple.c.
References element::d, element::data, element::i, logbuf, logptr, print_tuple(), element::s, element::t, and element::tag.
Referenced by print_tuple().
void print_element_stderr (struct element * e)
Definition at line 189 of file tuple.c.
References element::d, element::data, element::i, print_tuple_stderr(), element::s, element::t, and element::tag.
Referenced by print_tuple_stderr().
void print_tuple (struct tuple * s)
Definition at line 236 of file tuple.c.
References tuple::elements, logbuf, LOGBUFSIZE, logptr, tuple::num_elts, and print_element().
Referenced by print_element(), tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().
void print_tuple_stderr (struct tuple * s)
Definition at line 263 of file tuple.c.
References tuple::elements, logbuf, logptr, tuple::num_elts, and print_element_stderr().
Referenced by get_nb_tuple(), print_element_stderr(), and read_tuple().
int put_tuple (struct tuple * s, struct context * ctx)
Definition at line 785 of file tuple.c.
References context::id, open_client_socket(), PERROR, PUT, recv_chunk(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_put_tuple(), and main().
unsigned int random_int (void)
Return a 32-bit random unsigned integer, gotten from /dev/urandom.
Definition at line 453 of file tuple.c.
Referenced by main(), and py_random_int().
struct tuple* read_nb_tuple (struct tuple * template_tuple, struct context * ctx) [read]
Definition at line 1001 of file tuple.c.
References DBGPRINTF, context::id, open_client_socket(), PERROR, READ_NB, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_read_nb_tuple().
struct tuple* read_tuple (struct tuple * template_tuple, struct context * ctx) [read]
Definition at line 906 of file tuple.c.
References DBGPRINTF, context::id, open_client_socket(), PERROR, print_tuple_stderr(), READ, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_read_tuple().
int recv_chunk (struct context * ctx, char * buf, int size)
Definition at line 577 of file tuple.c.
References i_am_server, context::id, PERROR, PRINTF, and context::sock.
Referenced by client_thread_func(), count_tuple_space(), dump_tuple_space(), handle_dump_count_space(), put_tuple(), recv_tuple(), and replace_tuple().
struct tuple* recv_tuple (struct context * ctx) [read]
Definition at line 626 of file tuple.c.
References element::data, tuple::elements, EXIT, tuple::num_elts, PERROR, PRINTF, recv_chunk(), recv_tuple(), element::s, tuple::string_length, tuple::string_space, element::t, and element::tag.
Referenced by client_thread_func(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), read_nb_tuple(), read_tuple(), and recv_tuple().
int replace_tuple (struct tuple * template, struct tuple * replacement, struct context * ctx)
Definition at line 823 of file tuple.c.
References context::id, open_client_socket(), PERROR, recv_chunk(), REPLACE, send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_replace_tuple().
int send_chunk (struct context * ctx, char * buf, int bytes_to_send)
Definition at line 471 of file tuple.c.
References i_am_server, context::id, PERROR, PRINTF, and context::sock.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), handle_get_read(), put_tuple(), read_nb_tuple(), read_tuple(), replace_tuple(), send_tuple(), and tuple_server_log().
int send_tuple (struct context * ctx, struct tuple * t)
Definition at line 501 of file tuple.c.
References element::data, tuple::elements, tuple::num_elts, PERROR, element::ptr, element::s, send_chunk(), send_tuple(), tuple::string_length, and element::tag.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), handle_get_read(), put_tuple(), read_nb_tuple(), read_tuple(), replace_tuple(), and send_tuple().
double tuple_double_field (struct tuple * s, int n)
Definition at line 1265 of file tuple.c.
References element::d, element::data, EXIT, logbuf, logptr, print_tuple(), element::tag, and tuple_field().
static struct element* tuple_field (struct tuple * s, int n) [static, read]
Definition at line 1229 of file tuple.c.
References tuple::elements, EXIT, and tuple::num_elts.
Referenced by tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().
int tuple_int_field (struct tuple * s, int n)
Definition at line 1244 of file tuple.c.
References element::data, EXIT, element::i, logbuf, logptr, print_tuple(), element::tag, and tuple_field().
int tuple_server_log (FILE * stream, struct context * ctx)
Definition at line 1182 of file tuple.c.
References context::id, LOG, LOGBUFSIZE, open_client_socket(), PERROR, send_chunk(), and context::sock.
Referenced by ctx_tuple_server_log().
char* tuple_string_field (struct tuple * s, int * len, int n)
Definition at line 1286 of file tuple.c.
References element::data, EXIT, logbuf, logptr, print_tuple(), element::s, element::tag, and tuple_field().
Referenced by main().
struct tuple * tuple_tuple_field (struct tuple * s, int n) [read]
Definition at line 1309 of file tuple.c.
References element::data, EXIT, logbuf, logptr, print_tuple(), element::t, element::tag, and tuple_field().
int tuples_match (struct tuple * s, struct tuple * t)
Definition at line 396 of file tuple.c.
References element::d, element::data, tuple::elements, element::i, tuple::num_elts, element::s, element::t, element::tag, and tuples_match().
Referenced by handle_dump_count_space(), handle_get_read(), handle_replace(), and tuples_match().
Variable Documentation
int i_am_server = 0
This flag tells whether or not the current executable is the tuple server. If it is, then broken pipes on sockets should not crash the executable.
Doxygen likes LaTeX-flavored math:
Definition at line 79 of file tuple.c.
Referenced by main(), recv_chunk(), and send_chunk().
char logbuf[LOGBUFSIZE]
Buffer for logging tuple activity.
See also:
tuple_server_log
Definition at line 89 of file tuple.c.
Referenced by client_thread_func(), print_element(), print_tuple(), print_tuple_stderr(), tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().
int logptr = 0
Pointer into logbuf.
Definition at line 93 of file tuple.c.
Referenced by client_thread_func(), print_element(), print_tuple(), print_tuple_stderr(), tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().