tuple_server.c File Reference
tuple_server.c File Reference
The tuple server accepts incoming TCP connections and offers clients access to the database.
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/tcp.h>
#include <pthread.h>
#include <semaphore.h>
#include <malloc.h>
#include "tuple.h"
Data Structures
struct ttuple
Doubly-linked list of tuples, for efficient insertions and deletions.
Defines
#define GETLOG if (pthread_mutex_lock(&log_mutex)) perror("pthread_mutex_lock");
#define YIELDLOG if (pthread_mutex_unlock(&log_mutex)) perror("pthread_mutex_unlock");
#define LOGPRINTF(fmt, a...) if (logptr<sizeof(logbuf)-80) { logptr += sprintf(logbuf+logptr, fmt, ##a); }
#define LOGTUPLE(s) print_tuple(s);
#define MAXNUMTHREADS 64
#define GETACCESS if (pthread_mutex_lock(&access_mutex)) perror("mutex_lock");
#define YIELDACCESS if (pthread_mutex_unlock(&access_mutex)) perror("mutex_unlock");
Typedefs
typedef void *(* threadfunction)(void *)
Functions
static void print_status (void)
static void print_thread_func (void *varg)
static void add_tuple_to_space (struct tuple *t)
static void remove_message_from_space (struct ttuple *s)
static void kill_this_thread (struct context *arg)
static void handle_get_read (struct context *ctx, struct tuple *s, int remove, int blocking)
static void handle_replace (struct context *ctx, struct tuple *template, struct tuple *replacement)
static void handle_dump_count_space (struct context *ctx, int dump)
static void * client_thread_func (void *varg)
int main (int argc, char *argv[])
Variables
pthread_mutex_t log_mutex
static struct ttuple * first_message = NULL
static struct ttuple * last_message = NULL
static struct context client_list [MAXNUMTHREADS]
static char status_list [MAXNUMTHREADS+1]
static pthread_mutex_t access_mutex
static pthread_mutex_t blocked_mutex
static pthread_cond_t blocked_cond
Detailed Description
The tuple server accepts incoming TCP connections and offers clients access to the database.
The tuple server is responsible for remaining stable while clients misbehave, and making sure that client operations are atomic. Client misbehavior can include things like badly-formed requests and dropped network sockets.
Definition in file tuple_server.c.
Define Documentation
#define GETACCESS if (pthread_mutex_lock(&access_mutex)) perror("mutex_lock");
Definition at line 148 of file tuple_server.c.
Referenced by add_tuple_to_space(), handle_dump_count_space(), handle_get_read(), and handle_replace().
#define GETLOG if (pthread_mutex_lock(&log_mutex)) perror("pthread_mutex_lock");
Definition at line 90 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), handle_replace(), and kill_this_thread().
#define LOGPRINTF (fmt, a...) if (logptr<sizeof(logbuf)-80) { logptr += sprintf(logbuf+logptr, fmt, ##a); }
Definition at line 96 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), handle_replace(), and kill_this_thread().
#define LOGTUPLE (s) print_tuple(s);
Definition at line 98 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), and handle_replace().
#define MAXNUMTHREADS 64
Definition at line 125 of file tuple_server.c.
Referenced by main(), and print_status().
#define YIELDACCESS if (pthread_mutex_unlock(&access_mutex)) perror("mutex_unlock");
Definition at line 150 of file tuple_server.c.
Referenced by add_tuple_to_space(), handle_dump_count_space(), handle_get_read(), and handle_replace().
#define YIELDLOG if (pthread_mutex_unlock(&log_mutex)) perror("pthread_mutex_unlock");
Definition at line 92 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), handle_replace(), and kill_this_thread().
Typedef Documentation
typedef void*(* threadfunction)(void *)
Definition at line 683 of file tuple_server.c.
Function Documentation
static void add_tuple_to_space (struct tuple * t) [static]
When we add a tuple to the space, we unblock all the clients who are waiting for tuples, so they can check and see if this is the one they want.
Definition at line 198 of file tuple_server.c.
References blocked_cond, blocked_mutex, GETACCESS, ttuple::next, ttuple::previous, ttuple::tuple, and YIELDACCESS.
Referenced by client_thread_func(), handle_get_read(), and handle_replace().
static void* client_thread_func (void * varg) [static]
When a client makes a connection, find out what it wants, and do that operation.
Definition at line 510 of file tuple_server.c.
References add_tuple_to_space(), client_list, COUNT, DUMP, GET, GET_NB, GETLOG, handle_dump_count_space(), handle_get_read(), handle_replace(), context::id, kill_this_thread(), LOG, logbuf, LOGPRINTF, logptr, LOGTUPLE, context::peername, PUT, READ, READ_NB, recv_chunk(), recv_tuple(), REPLACE, SHUTDOWN_SOCKET, context::sock, status_list, context::thr, and YIELDLOG.
Referenced by main().
static void handle_dump_count_space (struct context * ctx, int dump) [static]
When a client requests a dump or a count of the tuple space, handle that here.
Definition at line 430 of file tuple_server.c.
References GETACCESS, tuple_list::next, ttuple::next, recv_chunk(), recv_tuple(), send_chunk(), send_tuple(), tuple_list::tup, ttuple::tuple, tuples_match(), and YIELDACCESS.
Referenced by client_thread_func().
static void handle_get_read (struct context * ctx, struct tuple * s, int remove, int blocking) [static]
Handle GETs and READs, both blocking and non-blocking.
Definition at line 294 of file tuple_server.c.
References add_tuple_to_space(), blocked_cond, blocked_mutex, client_list, DBGPRINTF, destroy_tuple(), GETACCESS, GETLOG, context::id, LOGPRINTF, LOGTUPLE, ttuple::next, context::peername, PRINTF, remove_message_from_space(), send_chunk(), send_tuple(), context::sock, status_list, ttuple::tuple, tuples_match(), YIELDACCESS, and YIELDLOG.
Referenced by client_thread_func().
static void handle_replace (struct context * ctx, struct tuple * template, struct tuple * replacement) [static]
Handle REPLACE. This operation will not block.
Definition at line 385 of file tuple_server.c.
References add_tuple_to_space(), client_list, destroy_tuple(), GETACCESS, GETLOG, context::id, LOGPRINTF, LOGTUPLE, ttuple::next, context::peername, remove_message_from_space(), REPLACE, SHUTDOWN_SOCKET, context::sock, status_list, ttuple::tuple, tuples_match(), YIELDACCESS, and YIELDLOG.
Referenced by client_thread_func().
static void kill_this_thread (struct context * arg) [static]
Definition at line 268 of file tuple_server.c.
References client_list, GETLOG, context::id, LOGPRINTF, context::peername, context::sock, status_list, context::thr, and YIELDLOG.
Referenced by client_thread_func().
int main (int argc, char * argv[])
Set up a socket to listen for incoming requests. When one arrives, start a pthread to handle it, and run client_thread_func().
Definition at line 690 of file tuple_server.c.
References access_mutex, blocked_cond, blocked_mutex, client_list, client_thread_func(), EXIT, i_am_server, context::id, log_mutex, MAXNUMTHREADS, print_thread_func(), context::sock, status_list, and context::thr.
static void print_status (void) [static]
Definition at line 168 of file tuple_server.c.
References MAXNUMTHREADS, and status_list.
Referenced by print_thread_func().
static void print_thread_func (void * varg) [static]
Definition at line 182 of file tuple_server.c.
References print_status().
Referenced by main().
static void remove_message_from_space (struct ttuple * s) [static]
Tuples are kept in a doubly-linked list, so there's a lot of pointer-hacking here.
Definition at line 239 of file tuple_server.c.
References ttuple::next, and ttuple::previous.
Referenced by handle_get_read(), and handle_replace().
Variable Documentation
pthread_mutex_t access_mutex [static]
Semaphore to make sure that all tuple operations are atomic. Each client finishes his operation before the next guy is allowed to begin.
Definition at line 147 of file tuple_server.c.
Referenced by main().
pthread_cond_t blocked_cond [static]
Definition at line 164 of file tuple_server.c.
Referenced by add_tuple_to_space(), handle_get_read(), and main().
pthread_mutex_t blocked_mutex [static]
When threads/clients block, they wait for this semaphore.
Definition at line 163 of file tuple_server.c.
Referenced by add_tuple_to_space(), handle_get_read(), and main().
struct context client_list[MAXNUMTHREADS] [static]
Maintain a list of the clients currently trying to access tuple space. Keep track of a pthread and a socket for each one.
Definition at line 131 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), handle_replace(), kill_this_thread(), and main().
struct ttuple* first_message = NULL [static]
Pointer to the first tuple in tuple space. When there is a GET or READ operation, the search begins with the first tuple.
Definition at line 115 of file tuple_server.c.
struct ttuple* last_message = NULL [static]
Pointer to the last tuple in tuple space. When there is a PUT operation, the tuple is put at the end of the list.
Definition at line 121 of file tuple_server.c.
pthread_mutex_t log_mutex
Definition at line 89 of file tuple_server.c.
Referenced by main().
char status_list[MAXNUMTHREADS+1] [static]
Definition at line 132 of file tuple_server.c.
Referenced by client_thread_func(), handle_get_read(), handle_replace(), kill_this_thread(), main(), and print_status().