tuple.h File Reference
tuple.h File Reference
Data Structures
struct element
The representation of a tuple element in C code, in both the server and a C client.
struct tuple
An ordered sequence of data values: integers, floats, strings. If this is a template (used during GET and READ operations to match existing tuples), an element can also be a wildcard.
struct tuple_list
Convenience struct, for when somebody needs to make a quick list of tuples.
struct context
The information we need to keep track of a client-server connection.
Defines
#define va_list __gnuc_va_list
#define _DBG_(x)
#define ASSERT(cond)
#define DBGPRINTF(fmt, a...)
#define PRINTF(fmt, a...) fprintf(stderr, __FILE__ ":%d " fmt, __LINE__, ##a)
#define PERROR(x) fprintf(stderr, __FILE__":%d ", __LINE__); perror(x)
#define TELL(x) DBGPRINTF(#x " = %d\n", x)
#define MALLOC malloc
#define FREE free
#define EXIT() exit(1)
#define TIMEVAL_DIFF(before, after)
#define SHUTDOWN_SOCKET(S, HOW)
#define SERVERNAME_ENVVAR "LINUXTUPLES_HOST"
#define PORTNUMBER_ENVVAR "LINUXTUPLES_PORT"
#define LOGBUFSIZE 32768
Enumerations
enum message_op {
PUT = 0, GET = 1, READ = 2, GET_NB = 3,
READ_NB = 4, DUMP = 5, COUNT = 6, LOG = 7,
REPLACE = 8
}
Functions
int get_server_portnumber (struct context *ctx)
void print_element (struct element *e)
void print_tuple (struct tuple *s)
struct tuple * make_tuple (char *fmt,...)
void destroy_tuple (struct tuple *t)
int tuples_match (struct tuple *s, struct tuple *t)
unsigned int random_int (void)
int send_chunk (struct context *ctx, char *buf, int bytes_to_send)
int send_tuple (struct context *ctx, struct tuple *t)
int recv_chunk (struct context *ctx, char *buf, int size)
struct tuple * recv_tuple (struct context *ctx)
int put_tuple (struct tuple *s, struct context *ctx)
int replace_tuple (struct tuple *template, struct tuple *replacement, struct context *ctx)
struct tuple * get_tuple (struct tuple *s, struct context *ctx)
struct tuple * read_tuple (struct tuple *s, struct context *ctx)
struct tuple * get_nb_tuple (struct tuple *s, struct context *ctx)
struct tuple * read_nb_tuple (struct tuple *s, struct context *ctx)
struct tuple_list * dump_tuple_space (struct tuple_list *templates, struct context *ctx)
int count_tuple_space (struct tuple_list *templates, struct context *ctx, int *result)
int tuple_server_log (FILE *stream, struct context *ctx)
int tuple_int_field (struct tuple *s, int n)
double tuple_double_field (struct tuple *s, int n)
char * tuple_string_field (struct tuple *s, int *len, int n)
Variables
int i_am_server
char logbuf [LOGBUFSIZE]
int logptr
Define Documentation
#define _DBG_ (x)
Definition at line 45 of file tuple.h.
#define ASSERT (cond)
Value:
_DBG_(if (!(cond)) { DBGPRINTF("assert failed: %s\n", \
                                  #cond); exit(1); })
Definition at line 48 of file tuple.h.
#define DBGPRINTF (fmt, a...)
Value:
_DBG_(fprintf(stderr, "%d  " __FILE__ ":%d " fmt, \
                 debug_counter++, __LINE__, ##a))
Definition at line 52 of file tuple.h.
Referenced by dump_tuple_space(), get_tuple(), handle_get_read(), read_nb_tuple(), and read_tuple().
#define EXIT () exit(1)
Definition at line 95 of file tuple.h.
Referenced by main(), make_tuple_internal(), recv_tuple(), tuple_double_field(), tuple_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().
#define FREE free
Definition at line 88 of file tuple.h.
#define LOGBUFSIZE 32768
Definition at line 283 of file tuple.h.
Referenced by print_tuple(), and tuple_server_log().
#define MALLOC malloc
Definition at line 87 of file tuple.h.
#define PERROR (x) fprintf(stderr, __FILE__":%d ", __LINE__); perror(x)
Definition at line 61 of file tuple.h.
#define PORTNUMBER_ENVVAR "LINUXTUPLES_PORT"
Definition at line 118 of file tuple.h.
Referenced by get_server_portnumber().
#define PRINTF (fmt, a...) fprintf(stderr, __FILE__ ":%d " fmt, __LINE__, ##a)
Definition at line 57 of file tuple.h.
Referenced by handle_get_read(), recv_chunk(), recv_tuple(), and send_chunk().
#define SERVERNAME_ENVVAR "LINUXTUPLES_HOST"
Definition at line 117 of file tuple.h.
Referenced by get_server_portnumber().
#define SHUTDOWN_SOCKET (S, HOW)
Value:
if (shutdown(S, HOW)) \
        { \
                PERROR("shutdown"); \
        }
Definition at line 106 of file tuple.h.
Referenced by client_thread_func(), get_nb_tuple(), get_tuple(), handle_replace(), put_tuple(), read_nb_tuple(), read_tuple(), and replace_tuple().
#define TELL (x) DBGPRINTF(#x " = %d\n", x)
Definition at line 65 of file tuple.h.
#define TIMEVAL_DIFF (before, after)
Value:
((after.tv_sec - before.tv_sec) + \
        1.0e-6 * (after.tv_usec - before.tv_usec))
Definition at line 100 of file tuple.h.
Referenced by main().
#define va_list __gnuc_va_list
Definition at line 39 of file tuple.h.
Referenced by make_tuple().
Enumeration Type Documentation
enum message_op
Enumerator:
PUT
GET
READ
GET_NB
READ_NB
DUMP
COUNT
LOG
REPLACE
Definition at line 120 of file tuple.h.
Function Documentation
int count_tuple_space (struct tuple_list * templates, struct context * ctx, int * result)
This works just like dump_tuple_space, but instead of sending back a list of all the matching tuples, we just send back a count of how many tuples match.
Definition at line 1134 of file tuple.c.
References COUNT, tuple_list::next, open_client_socket(), PERROR, recv_chunk(), send_chunk(), and send_tuple().
Referenced by ctx_count_tuple_space().
void destroy_tuple (struct tuple * t)
Deallocate all the storage for a tuple.
Definition at line 381 of file tuple.c.
References tuple::elements, and tuple::string_space.
Referenced by ctx_get_read(), ctx_put_tuple(), ctx_replace_tuple(), handle_get_read(), handle_replace(), and main().
struct tuple_list* dump_tuple_space (struct tuple_list * templates, struct context * ctx) [read]
Transmit a list of templates to the server, with an op code of DUMP. The server will respond by sending back a list of the matching tuples.
Definition at line 1057 of file tuple.c.
References DBGPRINTF, DUMP, tuple_list::next, open_client_socket(), PERROR, recv_chunk(), recv_tuple(), send_chunk(), send_tuple(), and tuple_list::tup.
Referenced by ctx_dump_tuple_space().
struct tuple* get_nb_tuple (struct tuple * s, struct context * ctx) [read]
Definition at line 953 of file tuple.c.
References GET_NB, context::id, open_client_socket(), PERROR, print_tuple_stderr(), recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_get_nb_tuple().
int get_server_portnumber (struct context * ctx)
Attempt to get the server name and port number from environment variables.
Returns:
0 if successful, 1 otherwise.
Definition at line 110 of file tuple.c.
References context::peername, context::portnumber, PORTNUMBER_ENVVAR, and SERVERNAME_ENVVAR.
Referenced by main(), and new_ctx().
struct tuple* get_tuple (struct tuple * s, struct context * ctx) [read]
Definition at line 864 of file tuple.c.
References DBGPRINTF, GET, context::id, open_client_socket(), PERROR, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_get_tuple(), and main().
struct tuple* make_tuple (char * fmt, ...) [read]
Create a tuple or template, starting from a printf-style variable argument list.
Definition at line 366 of file tuple.c.
References make_tuple_internal(), and va_list.
Referenced by main().
void print_element (struct element * e)
Definition at line 134 of file tuple.c.
References element::d, element::data, element::i, logbuf, logptr, print_tuple(), element::s, element::t, and element::tag.
Referenced by print_tuple().
void print_tuple (struct tuple * s)
int put_tuple (struct tuple * s, struct context * ctx)
Definition at line 785 of file tuple.c.
References context::id, open_client_socket(), PERROR, PUT, recv_chunk(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_put_tuple(), and main().
unsigned int random_int (void)
Return a 32-bit random unsigned integer, gotten from /dev/urandom.
Definition at line 453 of file tuple.c.
Referenced by main(), and py_random_int().
struct tuple* read_nb_tuple (struct tuple * s, struct context * ctx) [read]
Definition at line 1001 of file tuple.c.
References DBGPRINTF, context::id, open_client_socket(), PERROR, READ_NB, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_read_nb_tuple().
struct tuple* read_tuple (struct tuple * s, struct context * ctx) [read]
Definition at line 906 of file tuple.c.
References DBGPRINTF, context::id, open_client_socket(), PERROR, print_tuple_stderr(), READ, recv_tuple(), send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_read_tuple().
int recv_chunk (struct context * ctx, char * buf, int size)
Definition at line 577 of file tuple.c.
References i_am_server, context::id, PERROR, PRINTF, and context::sock.
Referenced by client_thread_func(), count_tuple_space(), dump_tuple_space(), handle_dump_count_space(), put_tuple(), recv_tuple(), and replace_tuple().
struct tuple* recv_tuple (struct context * ctx) [read]
Definition at line 626 of file tuple.c.
References element::data, tuple::elements, EXIT, tuple::num_elts, PERROR, PRINTF, recv_chunk(), recv_tuple(), element::s, tuple::string_length, tuple::string_space, element::t, and element::tag.
Referenced by client_thread_func(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), read_nb_tuple(), read_tuple(), and recv_tuple().
int replace_tuple (struct tuple * template, struct tuple * replacement, struct context * ctx)
Definition at line 823 of file tuple.c.
References context::id, open_client_socket(), PERROR, recv_chunk(), REPLACE, send_chunk(), send_tuple(), SHUTDOWN_SOCKET, and context::sock.
Referenced by ctx_replace_tuple().
int send_chunk (struct context * ctx, char * buf, int bytes_to_send)
Definition at line 471 of file tuple.c.
References i_am_server, context::id, PERROR, PRINTF, and context::sock.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), handle_get_read(), put_tuple(), read_nb_tuple(), read_tuple(), replace_tuple(), send_tuple(), and tuple_server_log().
int send_tuple (struct context * ctx, struct tuple * t)
Definition at line 501 of file tuple.c.
References element::data, tuple::elements, tuple::num_elts, PERROR, element::ptr, element::s, send_chunk(), send_tuple(), tuple::string_length, and element::tag.
Referenced by count_tuple_space(), dump_tuple_space(), get_nb_tuple(), get_tuple(), handle_dump_count_space(), handle_get_read(), put_tuple(), read_nb_tuple(), read_tuple(), replace_tuple(), and send_tuple().
double tuple_double_field (struct tuple * s, int n)
Definition at line 1265 of file tuple.c.
References element::d, element::data, EXIT, logbuf, logptr, print_tuple(), element::tag, and tuple_field().
int tuple_int_field (struct tuple * s, int n)
Definition at line 1244 of file tuple.c.
References element::data, EXIT, element::i, logbuf, logptr, print_tuple(), element::tag, and tuple_field().
int tuple_server_log (FILE * stream, struct context * ctx)
Definition at line 1182 of file tuple.c.
References context::id, LOG, LOGBUFSIZE, open_client_socket(), PERROR, send_chunk(), and context::sock.
Referenced by ctx_tuple_server_log().
char* tuple_string_field (struct tuple * s, int * len, int n)
Definition at line 1286 of file tuple.c.
References element::data, EXIT, logbuf, logptr, print_tuple(), element::s, element::tag, and tuple_field().
Referenced by main().
int tuples_match (struct tuple * s, struct tuple * t)
Definition at line 396 of file tuple.c.
References element::d, element::data, tuple::elements, element::i, tuple::num_elts, element::s, element::t, element::tag, and tuples_match().
Referenced by handle_dump_count_space(), handle_get_read(), handle_replace(), and tuples_match().
Variable Documentation
int i_am_server
This flag tells whether or not the current executable is the tuple server. If it is, then broken pipes on sockets should not crash the executable.
Doxygen likes LaTeX-flavored math:
Definition at line 79 of file tuple.c.
Referenced by main(), recv_chunk(), and send_chunk().
char logbuf[LOGBUFSIZE]
Buffer for logging tuple activity.
See also:
tuple_server_log
Definition at line 89 of file tuple.c.
Referenced by client_thread_func(), print_element(), print_tuple(), print_tuple_stderr(), tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().
int logptr
Pointer into logbuf.
Definition at line 93 of file tuple.c.
Referenced by client_thread_func(), print_element(), print_tuple(), print_tuple_stderr(), tuple_double_field(), tuple_int_field(), tuple_string_field(), and tuple_tuple_field().