tuple_client.c File Reference
tuple_client.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "tuple.h"
Defines
#define PARALLEL 4
#define N 8 * 1024
Functions
int main (int argc, char *argv[])
Define Documentation
#define N 8 * 1024
Definition at line 50 of file tuple_client.c.
Referenced by main().
#define PARALLEL 4
Definition at line 48 of file tuple_client.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Put out requests to have FFT operations done, and measure how long it takes to get the results back.
Definition at line 57 of file tuple_client.c.
References element::data, destroy_tuple(), tuple::elements, get_server_portnumber(), get_tuple(), element::i, make_tuple(), N, PARALLEL, context::peername, context::portnumber, put_tuple(), random_int(), and TIMEVAL_DIFF.