#!/usr/local/bin/guile -s
!#
;;; wwwcat --- a trivial ‘cat’ program for WWW resources

;; Copyright (C) 1997, 2001, 2003 Free Software Foundation, Inc.
;;
;; This file is part of Guile-WWW.
;;
;; Guile-WWW is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 3, or
;; (at your option) any later version.
;;
;; Guile-WWW is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public
;; License along with Guile-WWW; see the file COPYING.  If not,
;; write to the Free Software Foundation, Inc., 51 Franklin Street,
;; Fifth Floor, Boston, MA  02110-1301  USA

(use-modules (www main))

(if (> (length (program-arguments)) 1)
    (display (www:get (list-ref (program-arguments) 1)))
    (display "wwwcat: no document specified" (current-error-port)))

;;; wwwcat ends here
